extends Node

# -crab dance- DRAGON WINGS ARE DEAD -cm37
func _init():
	# Accessory Overwrites
	var overwrite_fez = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/fez.tres")
	overwrite_fez.take_over_path("res://objects/items/resources/accessories/hats/fez.tres")
	var overwrite_fishing = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/fishing_hat.tres")
	overwrite_fishing.take_over_path("res://objects/items/resources/accessories/hats/fishing_hat.tres")
	var overwrite_heartband = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/heart_headband.tres")
	overwrite_heartband.take_over_path("res://objects/items/resources/accessories/hats/heart_headband.tres")
	var overwrite_jester = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/jester_hat.tres")
	overwrite_jester.take_over_path("res://objects/items/resources/accessories/hats/jester_hat.tres")
	var overwrite_propeller = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/propeller_hat.tres")
	overwrite_propeller.take_over_path("res://objects/items/resources/accessories/hats/propeller_hat.tres")
	var overwrite_roman = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/roman_helmet.tres")
	overwrite_roman.take_over_path("res://objects/items/resources/accessories/hats/roman_helmet.tres")
	var overwrite_safari = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/safari_hat.tres")
	overwrite_safari.take_over_path("res://objects/items/resources/accessories/hats/safari_hat.tres")
	var overwrite_aviators = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/aviator_glasses.tres")
	overwrite_aviators.take_over_path("res://objects/items/resources/accessories/glasses/aviator_glasses.tres")
	var overwrite_smooch = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/smooch_glasses.tres")
	overwrite_smooch.take_over_path("res://objects/items/resources/accessories/glasses/smooch_glasses.tres")
	var overwrite_star = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/star_glasses.tres")
	overwrite_star.take_over_path("res://objects/items/resources/accessories/glasses/star_glasses.tres")
	var overwrite_bee = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/bee_wings.tres")
	overwrite_bee.take_over_path("res://objects/items/resources/accessories/backpacks/bee_wings.tres")
	var overwrite_dragon = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/dragon_wings.tres")
	overwrite_dragon.take_over_path("res://objects/items/resources/accessories/backpacks/dragon_wings.tres")
	var overwrite_gagpack = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/gag_pack.tres")
	overwrite_gagpack.take_over_path("res://objects/items/resources/accessories/backpacks/gag_pack.tres")
	var overwrite_spiderlegs = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/spider_legs.tres")
	overwrite_spiderlegs.take_over_path("res://objects/items/resources/accessories/backpacks/spider_legs.tres")
	var overwrite_smallpouch = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/small_pouch.tres")
	overwrite_smallpouch.take_over_path("res://objects/items/resources/accessories/backpacks/small_pouch.tres")
	var overwrite_medpouch = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/medium_pouch.tres")
	overwrite_medpouch.take_over_path("res://objects/items/resources/accessories/backpacks/medium_pouch.tres")
	var overwrite_largepouch = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/large_pouch.tres")
	overwrite_largepouch.take_over_path("res://objects/items/resources/accessories/backpacks/large_pouch.tres")
	var overwrite_superboots = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/super_toon_boots.tres")
	overwrite_superboots.take_over_path("res://objects/items/resources/accessories/shoes/super_toon_boots.tres")
	var overwrite_rolodex = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/rolodex.tres")
	overwrite_rolodex.take_over_path("res://objects/items/resources/passive/rolodex.tres")
	var overwrite_batwings = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/bat_wings.tres")
	overwrite_batwings.take_over_path("res://objects/items/resources/accessories/backpacks/bat_wings.tres")
	var overwrite_scubamask = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/scuba_mask.tres")
	overwrite_scubamask.take_over_path("res://objects/items/resources/accessories/glasses/scuba_mask.tres")
	var overwrite_scubatank = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/scuba_tank.tres")
	overwrite_scubatank.take_over_path("res://objects/items/resources/accessories/backpacks/scuba_tank.tres")
	var overwrite_pixie = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/pixie_wings.tres")
	overwrite_pixie.take_over_path("res://objects/items/resources/accessories/backpacks/pixie_wings.tres")
	
	# Anomaly Overwrites
	var overwrite_faulty = load("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/anomalies/floor_mod_level_down.gd")
	overwrite_faulty.take_over_path("res://scenes/game_floor/floor_modifiers/scripts/anomalies/floor_mod_level_down.gd")
	var overwrite_tightened = load("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/anomalies/floor_mod_level_up.gd")
	overwrite_tightened.take_over_path("res://scenes/game_floor/floor_modifiers/scripts/anomalies/floor_mod_level_up.gd")
	var overwrite_inspiration = load("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/anomalies/floor_mod_inspiration.gd")
	overwrite_inspiration.take_over_path("res://scenes/game_floor/floor_modifiers/scripts/anomalies/floor_mod_inspiration.gd")
	var overwrite_orggags = load("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/anomalies/floor_mod_organic_gags.gd")
	overwrite_orggags.take_over_path("res://scenes/game_floor/floor_modifiers/scripts/anomalies/floor_mod_organic_gags.gd")
	var overwrite_sillywaves = load("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/anomalies/floor_mod_silly_waves.gd")
	overwrite_sillywaves.take_over_path("res://scenes/game_floor/floor_modifiers/scripts/anomalies/floor_mod_silly_waves.gd")
	var overwrite_dramaturgy = load("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/anomalies/floor_mod_stagnant_air.gd")
	overwrite_dramaturgy.take_over_path("res://scenes/game_floor/floor_modifiers/scripts/anomalies/floor_mod_stagnant_air.gd")
