extends Node

# -crab dance- DRAGON WINGS ARE DEAD -cm37
func _init():
	var overwrite_fez = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/fez.tres")
	overwrite_fez.take_over_path("res://objects/items/resources/accessories/hats/fez.tres")
	var overwrite_fishing = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/fishing_hat.tres")
	overwrite_fishing.take_over_path("res://objects/items/resources/accessories/hats/fishing_hat.tres")
	var overwrite_heartband = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/heart_headband.tres")
	overwrite_heartband.take_over_path("res://objects/items/resources/accessories/hats/heart_headband.tres")
	var overwrite_jester = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/jester_hat.tres")
	overwrite_jester.take_over_path("res://objects/items/resources/accessories/hats/jester_hat.tres")
	var overwrite_propeller = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/propeller_hat.tres")
	overwrite_propeller.take_over_path("res://objects/items/resources/accessories/hats/propeller_hat.tres")
	var overwrite_roman = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/roman_helmet.tres")
	overwrite_roman.take_over_path("res://objects/items/resources/accessories/hats/roman_helmet.tres")
	var overwrite_safari = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/safari_hat.tres")
	overwrite_safari.take_over_path("res://objects/items/resources/accessories/hats/safari_hat.tres")
	var overwrite_aviators = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/aviator_glasses.tres")
	overwrite_aviators.take_over_path("res://objects/items/resources/accessories/glasses/aviator_glasses.tres")
	var overwrite_smooch = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/smooch_glasses.tres")
	overwrite_smooch.take_over_path("res://objects/items/resources/accessories/glasses/smooch_glasses.tres")
	var overwrite_star = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/star_glasses.tres")
	overwrite_star.take_over_path("res://objects/items/resources/accessories/glasses/star_glasses.tres")
	var overwrite_bee = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/bee_wings.tres")
	overwrite_bee.take_over_path("res://objects/items/resources/accessories/backpacks/bee_wings.tres")
	var overwrite_dragon = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/dragon_wings.tres")
	overwrite_dragon.take_over_path("res://objects/items/resources/accessories/backpacks/dragon_wings.tres")
	var overwrite_gagpack = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/gag_pack.tres")
	overwrite_gagpack.take_over_path("res://objects/items/resources/accessories/backpacks/gag_pack.tres")
	var overwrite_spiderlegs = preload("res://mods-unpacked/CrazyMew37-EndlessMode/overwrites/spider_legs.tres")
	overwrite_spiderlegs.take_over_path("res://objects/items/resources/accessories/backpacks/spider_legs.tres")
